use lalrpop_util::ParseError;

use crate::keycode::Term;

grammar;

extern {
    type Error = String;
}

Key: Term = r"[a-zA-Z_][[:word:]]*" =>? Term::new_key(<>).ok_or_else(|| ParseError::User {
    error: <>.into(),
});
Mod: u8 = {
    "Control_L" => 0xe0,
    "Shift_L" => 0xe1,
    "Alt_L" => 0xe2,
    "Super_L" => 0xe3,
};

pub TermList = (Term)+;

Term = {
    Key,
    <Mod> "(" <TermList> ")" => Term::Mod(<>),
    
};
// vi:ft=rust
