#define STN_NUM  22
#define STN_S_   21
#define STN_T_   20
#define STN_K_   19
#define STN_P_   18
#define STN_W_   17
#define STN_H_   16
#define STN_R_   15
#define STN_A    14
#define STN_O    13
#define STN_STAR 12
#define STN_E    11
#define STN_U    10
#define STN__F   9
#define STN__R   8
#define STN__P   7
#define STN__B   6
#define STN__L   5
#define STN__G   4
#define STN__T   3
#define STN__S   2
#define STN__D   1
#define STN__Z   0
